name: ci-testing
version: 0.2.3
summary: HTTP file serve & URL shortener
license: Apache-2.0
contact: jon.seager@canonical.com
issues: https://github.com/jnsgruk/gosherve/issues
source-code: https://github.com/jnsgruk/gosherve
website: https://gosherve.io
description: |
  A simple HTTP file server with some basic URL shortening/redirect functionality.
base: core22
grade: stable
confinement: strict
compression: lzo

apps:
  ci-testing:
    command: gosherve
    plugs:
      - home
      - network
      - network-bind

architectures:
  - build-on: amd64
  - build-on: arm64

parts:
  gosherve:
    plugin: go
    source: https://github.com/jnsgruk/gosherve
    source-type: git
    source-tag: "$SNAPCRAFT_PROJECT_VERSION"
    build-snaps: [go]
    build-environment:
      - CGO_ENABLED: "0"
      - LDFLAGS: "-s -w"
    override-build: |
      export LDFLAGS="${LDFLAGS} -X 'main.version=${SNAPCRAFT_PROJECT_VERSION}'"
      export LDFLAGS="${LDFLAGS} -X 'main.commit=$(git rev-parse HEAD)'"

      go build -ldflags "${LDFLAGS}" ./cmd/gosherve
      cp gosherve $SNAPCRAFT_PART_INSTALL/gosherve
    stage:
      - gosherve
