name: ci-testing
version: 0.2.3
summary: HTTP file serve & URL shortener
license: Apache-2.0
contact: jon.seager@canonical.com
issues: https://github.com/jnsgruk/ci-testing/issues
source-code: https://github.com/jnsgruk/ci-testing
description: |
  A simple test application
base: core22
grade: stable
confinement: strict
compression: lzo

apps:
  ci-testing:
    command: helloserver
    plugs:
      - home
      - network
      - network-bind

architectures:
  - build-on: amd64
  - build-on: arm64

parts:
  hello:
    plugin: go
    source: https://github.com/golang/example
    source-type: git
    build-snaps: [go]
    override-build: |
      cd helloserver
      go build -o helloserver ./server.go
      cp helloserver $CRAFT_PART_INSTALL/helloserver
