name: Promote

on:
  issue_comment:
    types:
      - created

permissions:
  issues: write

jobs:
  promote:
    name: ⬆️ Promote to stable
    environment: "Candidate Branch"
    runs-on: ubuntu-latest
    steps:
      - name: ⬆️ Promote to stable
        uses: jnsgruk/snapcrafters-ci/promote-to-stable@fix-snap-build-action
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          store-token: ${{ secrets.SNAP_STORE_STABLE }}
