name: 🧪 Build snap on amd64

on:
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: 🧪 Build snap on amd64
    runs-on: ubuntu-latest
    steps:
      - name: Build snap
        uses: jnsgruk/snapcrafters-ci/test-snap-build@main
