name: 🚢 Release to latest/candidate

on:
  # Run the workflow each time new commits are pushed to the candidate branch. 
  push:
    branches: [ "main" ]

permissions:
  contents: read
  issues: write

jobs:
  release:
    name: 🚢 Release to latest/candidate
    uses: jnsgruk/snapcrafters-ci/.github/workflows/release-to-candidate.yaml@main
    secrets:
      LP_BUILD_SECRET: ${{ secrets.LP_BUILD_SECRET }}
      SNAP_STORE_CANDIDATE: ${{ secrets.SNAP_STORE_CANDIDATE }}
      SNAPCRAFTERS_BOT_COMMIT: ${{ secrets.SNAPCRAFTERS_BOT_COMMIT }}

