name: 📦 Publish to candidate

on:
  # Run the workflow each time new commits are pushed to the candidate branch. 
  push:
    branches: [ "main" ]

jobs:
  publish-to-candidate:
    uses: jnsgruk/snapcrafters-ci/.github/workflows/snap-store-publish-to-candidate.yml@initial-build